baseURL = "http://localhost:1313"
title = "Matías Brown Blog"

theme = "puppet"

copyright = ""
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = "G-NPSX6WS1G3"

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "guide"
name = "Guides"
url = "/series/"
weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/matiasbrown/"
weight = 100


[params]
author = "Matías Brown"
description = "Welcome to my personal blog, where I share my experiences and knowledge as a developer."
keywords = "blog,developer,personal,ai,learn,technology"
img_home = "img/home-bg.jpeg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/avatar.png"
bio = " I'm a passionate software developer hailing from Argentina. Currently diving into the exciting realms of cloud development and the fascinating worlds of machine learning and data science."

[params.social]
github = "matiasbrown"
gitlab = "matiasbrown"
linkedin = "matiasbrown"
rss = true

# [[params.friends]]
# name = "Roberto"
# url = "https://gohugo.io"

# [[params.friends]]
# name = "Robertiño"
# url = "https://gohugo.io"

# See https://giscus.app/
[params.giscus]
enable = true
repo = "matiasbrown/matiasbrown.dev"
repo_id = "R_kgDOK0FXxg"
category = "Blog"
category_id = "DIC_kwDOK0FXxs4Cbbfn"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
loading = "lazy"
reactions_enabled = "1"
